# Generated by Django 4.0.6 on 2022-08-08 04:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_ordered_by_alter_order_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
            preserve_default=False,
        ),
    ]
