# Generated by Django 4.1 on 2022-08-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transportations', '0002_alter_transportation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('eta', models.TimeField(blank=True, null=True)),
                ('transportations', models.ManyToManyField(to='transportations.transportation')),
            ],
            options={
                'ordering': ['origin'],
            },
        ),
    ]
