# Generated by Django 4.0.6 on 2022-08-07 04:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transportations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('departure_time', models.TimeField(blank=True, null=True)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('eta', models.TimeField(blank=True, null=True)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('available_seats', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('total_passengers', models.IntegerField(default=0)),
                ('transportation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportation', to='transportations.transportation')),
            ],
            options={
                'ordering': ['origin'],
            },
        ),
    ]
