# Generated by Django 4.0.6 on 2022-08-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='arrival_time',
        ),
        migrations.AddField(
            model_name='trip',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
