# Generated by Django 4.1 on 2022-08-07 00:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_trip_available_seats_alter_trip_transportations'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
