# Generated by Django 4.1 on 2022-08-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Bis'), (2, 'Kapal'), (3, 'Kereta')], default=1),
        ),
    ]
