# Generated by Django 4.1 on 2022-08-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportations', '0002_alter_transportation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='units',
            field=models.IntegerField(null=True),
        ),
    ]
